- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Re-export NFS
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Reload sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: reloaded
