dots_repo: 0oAstro/dots
dots_prompt_args: "--no-tty --promptBool ai={{ chezmoi_data.ai | bool | lower }},server={{ chezmoi_data.server | bool | lower }}"
dots_controller_age_key: "{{ lookup('ansible.builtin.file', '~/.config/age/keys.txt', errors='ignore') | default('', true) }}"
