# tmux config

source-file -q "$HOME/.config/tmux/conf.d/options.conf"
source-file -q "$HOME/.config/tmux/conf.d/bindings.conf"

# Plugins / TPM. Keep this at the bottom.
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins"
source-file -q "$HOME/.config/tmux/conf.d/plugins.conf"
run-shell "$HOME/.config/tmux/plugins/tpm/tpm"

# Keep Ghostty transparency visible after the theme is loaded.
set-option -g status-style bg=default
set-window-option -g window-status-style "fg=default,bg=default,none"
set-window-option -g window-status-format "#[fg=default,bg=default] #I: #W "
set-window-option -g window-status-current-style "fg=colour214,bg=default,underscore"
set-window-option -g window-status-current-format "#[fg=colour214,bg=default,underscore] #I: #W "
