#!/usr/bin/env bash

# write temporary auto-plugins config
write_tmp_cfg() {
  local -r tmp_cfg="/tmp/mooks-auto-plugins.conf"

  # create config
  echo -e "# this file is autogenerated, do not edit\n" > "$tmp_cfg"
  echo "set -g @plugin 'tmux-plugins/tpm'" >> "$tmp_cfg"

  # add plugins from mooks-plugins list to config
  for plugin in "${plugins[@]}"; do
    echo "set -g @plugin '$plugin'" >> "$tmp_cfg"
  done

  # add command to initialize tpm (must be set at the very bottom of tmux.conf)
  echo "run '$TMUX_DIR/plugins/tpm/tpm'" >> "$tmp_cfg"
  echo "$tmp_cfg"
}

# init tpm and create/update auto-plugins config
init() {
  # create plugins dirs if not exist
  if [ ! -d "$(dirname "$AUTO_PLUGINS_CONF")" ] || [ ! -d "$PLUGINS_DIR" ]; then
    mkdir -p "$(dirname "$AUTO_PLUGINS_CONF")" "$PLUGINS_DIR"
  fi
  set_tmux_env -g TMUX_PLUGIN_MANAGER_PATH "$PLUGINS_DIR"

  # install tpm if not nstalled
  if [ ! -d "$PLUGINS_DIR/tpm" ]; then
    tmux display-message "Installing tmux-plugin-manager"
    git clone https://github.com/tmux-plugins/tpm "$PLUGINS_DIR/tpm" 2>/dev/null
  fi

  tmp_cfg=$(write_tmp_cfg)

  # replace auto_plugins config if it has changes
  if ! cmp -s "$tmp_cfg" "$AUTO_PLUGINS_CONF"; then
    mv "$tmp_cfg" "$AUTO_PLUGINS_CONF"
  fi
}

# clean/install/update plugins via tpm
update() {
  tmux display-message "Installing & updating plugins"

  # refresh plugins states
  cleaned=$("$TMUX_DIR/plugins/tpm/bin/clean_plugins")
  # shellcheck disable=SC2034 # catch output
  updated=$("$TMUX_DIR/plugins/tpm/bin/update_plugins all")
  installed=$("$TMUX_DIR/plugins/tpm/bin/install_plugins")

  # reload tmux.conf on plugin change
  if [[ "$cleaned" =~ .*Removing.* ]] || [[ "$installed" =~ .*Installing.* ]]; then
    tmux display-message "Plugins has changed, reloading config..."
    tmux source-file -F "#{@mooks-tmux-conf}"
  fi
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/lib/variables.sh"
source "$DIR/lib/utils.sh"

mooks_tpm_enable=$(get_tmux_option -g "$opt_mooks_tpm_enable")
mooks_plugins=$(get_tmux_option -g "$opt_mooks_plugins")
declare -r mooks_tpm_enable mooks_plugins

IFS=':' read -r -a plugins <<< "$mooks_plugins"

# exit if tpm is disabled
if [ "$mooks_tpm_enable" != "true" ]; then
  exit 0
fi

# check if git is installed
if ! command -v git &> /dev/null; then
  echo "error: git not found (required for plugins management)"
  exit 1
fi

for arg in "$@"; do
  if [ "$arg" = "init" ]; then init; fi
  if [ "$arg" = "update" ]; then update; fi
done
