#!/usr/bin/env bash
swaymsg -t get_tree | jq --unbuffered --compact-output '
(
  select(.name == "root") |
  .nodes[] |
  select(.name == "__i3") |
  .nodes[] |
  select(.name == "__i3_scratch") |
  .focus
) as $scratch_ids |
[
  .. |
  (.nodes? + .floating_nodes?) // empty |
  .[] |
  select(.id|IN($scratch_ids[]))
] as $scratch_nodes |
{ text: "\($scratch_nodes|length)", tooltip: $scratch_nodes|map(.name)|join("\n") }'
