name: ci
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash # with pipefail

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: sudo apt-get install -y zsh
        if: runner.os == 'Linux'
      - run: mise run check
